results_dir:    "results"
analysis_tab_file:
datasets_tab_file:
reads_raw_source: "/home/domenico/Research/developing/genomes_pipeline_data"

map_dir:    "map"
log_dir:    "logs"
tmp_dir:    "/tmp"
species: 
reads_raw: "data/reads/raw"

qc:
    qc: "qc"
    fastqc:
        raw: "qc/data/reads/raw"
        filtered: "qc/data/reads/filtered"

read_processing:
    trimmomatic:
        outdir: "data/reads/filtered"
        options: "-phred33"
        processing_options: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36"
        java_cmd: "java"
        #jar_file: "/crex/proj/uppstore2018171/conda_envs/mtoolbox-ark/share/trimmomatic/trimmomatic.jar"
        java_vm_mem: "4G"
        threads: 5

assembly:
    spades:
        outdir: "assembly/spades"
