results_dir:    "220822"
analysis_tab_file: "config_files/analysis.220822.tab"
datasets_tab_file: "config_files/datasets.220822.tab"
reads_raw_source: "/g100_work/ELIX5_simone/data/220822"

map_dir:    "map"
log_dir:    "logs"
tmp_dir:    "/tmp"
species: 
reads_raw: "data/reads/raw"

qc:
    qc: "qc"
    fastqc:
        raw: "qc/data/reads/raw"
        filtered: "qc/data/reads/filtered"

read_processing:
    kaiju:
        db:        "/g100_work/ELIX5_simone/data/kaiju/kaiju_db_refseq.fmi"
        nodes_dmp: "/g100_work/ELIX5_simone/data/kaiju/nodes.dmp"
        names_dmp: "/g100_work/ELIX5_simone/data/kaiju/names.dmp"
        threads: 12
    trimmomatic:
        outdir: "data/reads/filtered"
        options: "-phred33"
        processing_options: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36"
        java_cmd: "java"
        java_vm_mem: "4G"
        threads: 
        adapters: "all_adapters.fasta"

assembly:
    spades:
        outdir: "assembly/spades"

checkm:
    data_dir: "/g100_work/ELIX5_simone/data/checkm"

